export { default as logo } from "./logo.png";
export { default as logoLight } from "./logoLight.png";
export { default as homeBanner } from "./homeBanner.png";
export { default as kittedGraments } from "./kittedGraments.png";
export { default as womanGarments } from "./womanGarments.png";
export { default as workGarments } from "./workGarments.png";
export { default as quotationImage } from "./quotationImage.png";
export { default as sustainabilityImage } from "./sustainabilityImage.png";
export { default as knittedImage } from "./knittedImage.png";
